# Generated by Django 5.1.4 on 2025-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_cleanup_and_reseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
